MALL Customers

Data Processing in Pandas Introduction

Data processing is the process of collecting, cleaning, transforming, and analyzing data to extract useful information. Pandas is a powerful Python library that provides easy-to-use data structures and tools for efficient data processing.

Main Data Processing Operations in Pandas

Data Loading
Pandas can load data from various sources such as CSV, Excel, JSON, and databases into a DataFrame.

Data Inspection
Before processing, it is important to examine the dataset by checking its structure, columns, data types, and summary information.

Data Cleaning
Data cleaning involves:

Handling missing values Removing duplicate records Correcting inconsistent data Fixing data type issues 4. Data Filtering

Filtering allows users to select specific rows or columns based on given conditions.

Data Transformation
Transformation includes modifying existing data, creating new columns, and changing data formats to meet analysis requirements.

Data Sorting
Data can be arranged in ascending or descending order to improve readability and analysis.

Grouping and Aggregation
Data can be grouped by categories and summarized using functions such as sum, average, count, minimum, and maximum.

Data Merging
Multiple datasets can be combined into a single DataFrame using merge and join operations.

Data Analysis
Processed data can be analyzed to identify patterns, trends, and insights for decision-making.

Data Export
After processing, the cleaned and transformed data can be saved to files such as CSV or Excel for future use.

Conclusion

Pandas simplifies data processing by providing efficient tools for cleaning, organizing, transforming, and analyzing data. It is widely used in data science, machine learning, and business analytics.

In [ ]:
import pandas as pd
import numpy as np
 

df = pd.read_csv(r"Mall_Customers.csv")

print(df.head())

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [10]:
import os

print("Current Folder:")
print(os.getcwd())

print("\nFiles in this folder:")
print(os.listdir())

Current Folder:
c:\Users\ishik\45_Days_Training\pandas

Files in this folder:
['basic.ipynb', 'Dataprepocessing2.ipynb', 'Data_preprocessing.ipynb', 'ElectricCarData_Clean.csv', 'Mall_Customers.csv']

In [11]:
import os

print("Current Folder:")
print(os.getcwd())

print("\nFiles in this folder:")
print(os.listdir())

Current Folder:
c:\Users\ishik\45_Days_Training\pandas

Files in this folder:
['basic.ipynb', 'Dataprepocessing2.ipynb', 'Data_preprocessing.ipynb', 'ElectricCarData_Clean.csv', 'Mall_Customers.csv']

In [13]:
df.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [15]:
df.isnull()

     CustomerID  Genre    Age  Annual Income (k$)  Spending Score (1-100)
0         False  False  False               False                   False
1         False  False  False               False                   False
2         False  False  False               False                   False
3         False  False  False               False                   False
4         False  False  False               False                   False
..          ...    ...    ...                 ...                     ...
195       False  False  False               False                   False
196       False  False  False               False                   False
197       False  False  False               False                   False
198       False  False  False               False                   False
199       False  False  False               False                   False

[200 rows x 5 columns]

In [17]:
df.shape

(200, 5)

In [19]:
#to see the whole dataset

import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

print(df)

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
30           31    Male   60                  30                       4
31           32  Female   21                  30                      73
32           33    Male   53                  33                       4
33           34    Male   18                  33                      92
34           35  Female   49                  33                      14
35           36  Female   21                  33                      81
36           37  Female   42                  34                      17
37           38  Female   30                  34                      73
38           39  Female   36                  37                      26
39           40  Female   20                  37                      75
40           41  Female   65                  38                      35
41           42    Male   24                  38                      92
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
45           46  Female   24                  39                      65
46           47  Female   50                  40                      55
47           48  Female   27                  40                      47
48           49  Female   29                  40                      42
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
58           59  Female   27                  46                      51
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
61           62    Male   19                  46                      55
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
65           66    Male   18                  48                      59
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
68           69    Male   19                  48                      59
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
75           76    Male   26                  54                      54
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
78           79  Female   23                  54                      52
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
84           85  Female   21                  54                      57
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
87           88  Female   22                  57                      55
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
91           92    Male   18                  59                      41
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
95           96    Male   24                  60                      52
96           97  Female   47                  60                      47
97           98  Female   27                  60                      50
98           99    Male   48                  61                      42
99          100    Male   20                  61                      49
100         101  Female   23                  62                      41
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
103         104    Male   26                  62                      55
104         105    Male   49                  62                      56
105         106  Female   21                  62                      42
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
111         112  Female   19                  63                      54
112         113  Female   38                  64                      42
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
120         121    Male   27                  67                      56
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
124         125  Female   23                  70                      29
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
132         133  Female   25                  72                      34
133         134  Female   31                  72                      71
134         135    Male   20                  73                       5
135         136  Female   29                  73                      88
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
138         139    Male   19                  74                      10
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
142         143  Female   28                  76                      40
143         144  Female   32                  76                      87
144         145    Male   25                  77                      12
145         146    Male   28                  77                      97
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
155         156  Female   27                  78                      89
156         157    Male   37                  78                       1
157         158  Female   30                  78                      78
158         159    Male   34                  78                       1
159         160  Female   30                  78                      73
160         161  Female   56                  79                      35
161         162  Female   29                  79                      83
162         163    Male   19                  81                       5
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [24]:
#shows columns 
df.columns

Index(['CustomerID', 'Genre', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='str')

In [25]:
# to get info of dataset
df.info

<bound method DataFrame.info of      CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
30           31    Male   60                  30                       4
31           32  Female   21                  30                      73
32           33    Male   53                  33                       4
33           34    Male   18                  33                      92
34           35  Female   49                  33                      14
35           36  Female   21                  33                      81
36           37  Female   42                  34                      17
37           38  Female   30                  34                      73
38           39  Female   36                  37                      26
39           40  Female   20                  37                      75
40           41  Female   65                  38                      35
41           42    Male   24                  38                      92
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
45           46  Female   24                  39                      65
46           47  Female   50                  40                      55
47           48  Female   27                  40                      47
48           49  Female   29                  40                      42
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
58           59  Female   27                  46                      51
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
61           62    Male   19                  46                      55
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
65           66    Male   18                  48                      59
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
68           69    Male   19                  48                      59
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
75           76    Male   26                  54                      54
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
78           79  Female   23                  54                      52
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
84           85  Female   21                  54                      57
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
87           88  Female   22                  57                      55
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
91           92    Male   18                  59                      41
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
95           96    Male   24                  60                      52
96           97  Female   47                  60                      47
97           98  Female   27                  60                      50
98           99    Male   48                  61                      42
99          100    Male   20                  61                      49
100         101  Female   23                  62                      41
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
103         104    Male   26                  62                      55
104         105    Male   49                  62                      56
105         106  Female   21                  62                      42
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
111         112  Female   19                  63                      54
112         113  Female   38                  64                      42
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
120         121    Male   27                  67                      56
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
124         125  Female   23                  70                      29
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
132         133  Female   25                  72                      34
133         134  Female   31                  72                      71
134         135    Male   20                  73                       5
135         136  Female   29                  73                      88
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
138         139    Male   19                  74                      10
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
142         143  Female   28                  76                      40
143         144  Female   32                  76                      87
144         145    Male   25                  77                      12
145         146    Male   28                  77                      97
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
155         156  Female   27                  78                      89
156         157    Male   37                  78                       1
157         158  Female   30                  78                      78
158         159    Male   34                  78                       1
159         160  Female   30                  78                      73
160         161  Female   56                  79                      35
161         162  Female   29                  79                      83
162         163    Male   19                  81                       5
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83>

In [26]:
# to generate statistics
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [27]:
df["CustomerID"]

0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
9       10
10      11
11      12
12      13
13      14
14      15
15      16
16      17
17      18
18      19
19      20
20      21
21      22
22      23
23      24
24      25
25      26
26      27
27      28
28      29
29      30
30      31
31      32
32      33
33      34
34      35
35      36
36      37
37      38
38      39
39      40
40      41
41      42
42      43
43      44
44      45
45      46
46      47
47      48
48      49
49      50
50      51
51      52
52      53
53      54
54      55
55      56
56      57
57      58
58      59
59      60
60      61
61      62
62      63
63      64
64      65
65      66
66      67
67      68
68      69
69      70
70      71
71      72
72      73
73      74
74      75
75      76
76      77
77      78
78      79
79      80
80      81
81      82
82      83
83      84
84      85
85      86
86      87
87      88
88      89
89      90
90      91
91      92
92      93
93      94
94      95
95      96
96      97
97      98
98      99
99     100
100    101
101    102
102    103
103    104
104    105
105    106
106    107
107    108
108    109
109    110
110    111
111    112
112    113
113    114
114    115
115    116
116    117
117    118
118    119
119    120
120    121
121    122
122    123
123    124
124    125
125    126
126    127
127    128
128    129
129    130
130    131
131    132
132    133
133    134
134    135
135    136
136    137
137    138
138    139
139    140
140    141
141    142
142    143
143    144
144    145
145    146
146    147
147    148
148    149
149    150
150    151
151    152
152    153
153    154
154    155
155    156
156    157
157    158
158    159
159    160
160    161
161    162
162    163
163    164
164    165
165    166
166    167
167    168
168    169
169    170
170    171
171    172
172    173
173    174
174    175
175    176
176    177
177    178
178    179
179    180
180    181
181    182
182    183
183    184
184    185
185    186
186    187
187    188
188    189
189    190
190    191
191    192
192    193
193    194
194    195
195    196
196    197
197    198
198    199
199    200
Name: CustomerID, dtype: int64

In [28]:
#checks missing values
df.isnull().sum()

CustomerID                0
Genre                     0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [29]:
df[df["Age"] > 30]

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
4             5  Female   31                  17                      40
6             7  Female   35                  18                       6
8             9    Male   64                  19                       3
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
14           15    Male   37                  20                      13
16           17  Female   35                  21                      35
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
30           31    Male   60                  30                       4
32           33    Male   53                  33                       4
34           35  Female   49                  33                      14
36           37  Female   42                  34                      17
38           39  Female   36                  37                      26
40           41  Female   65                  38                      35
42           43    Male   48                  39                      36
43           44  Female   31                  39                      61
44           45  Female   49                  39                      28
46           47  Female   50                  40                      55
49           50  Female   31                  40                      42
50           51  Female   49                  42                      52
51           52    Male   33                  42                      60
52           53  Female   31                  43                      54
53           54    Male   59                  43                      60
54           55  Female   50                  43                      45
55           56    Male   47                  43                      41
56           57  Female   51                  44                      50
57           58    Male   69                  44                      46
59           60    Male   53                  46                      46
60           61    Male   70                  46                      56
62           63  Female   67                  47                      52
63           64  Female   54                  47                      59
64           65    Male   63                  48                      51
66           67  Female   43                  48                      50
67           68  Female   68                  48                      48
69           70  Female   32                  48                      47
70           71    Male   70                  49                      55
71           72  Female   47                  49                      42
72           73  Female   60                  50                      49
73           74  Female   60                  50                      56
74           75    Male   59                  54                      47
76           77  Female   45                  54                      53
77           78    Male   40                  54                      48
79           80  Female   49                  54                      42
80           81    Male   57                  54                      51
81           82    Male   38                  54                      55
82           83    Male   67                  54                      41
83           84  Female   46                  54                      44
85           86    Male   48                  54                      46
86           87  Female   55                  57                      58
88           89  Female   34                  58                      60
89           90  Female   50                  58                      46
90           91  Female   68                  59                      55
92           93    Male   48                  60                      49
93           94  Female   40                  60                      40
94           95  Female   32                  60                      42
96           97  Female   47                  60                      47
98           99    Male   48                  61                      42
101         102  Female   49                  62                      48
102         103    Male   67                  62                      59
104         105    Male   49                  62                      56
106         107  Female   66                  63                      50
107         108    Male   54                  63                      46
108         109    Male   68                  63                      43
109         110    Male   66                  63                      48
110         111    Male   65                  63                      52
112         113  Female   38                  64                      42
116         117  Female   63                  65                      43
117         118  Female   49                  65                      59
118         119  Female   51                  67                      43
119         120  Female   50                  67                      57
121         122  Female   38                  67                      40
122         123  Female   40                  69                      58
123         124    Male   39                  69                      91
125         126  Female   31                  70                      77
126         127    Male   43                  71                      35
127         128    Male   40                  71                      95
128         129    Male   59                  71                      11
129         130    Male   38                  71                      75
130         131    Male   47                  71                       9
131         132    Male   39                  71                      75
133         134  Female   31                  72                      71
136         137  Female   44                  73                       7
137         138    Male   32                  73                      73
139         140  Female   35                  74                      72
140         141  Female   57                  75                       5
141         142    Male   32                  75                      93
143         144  Female   32                  76                      87
146         147    Male   48                  77                      36
147         148  Female   32                  77                      74
148         149  Female   34                  78                      22
149         150    Male   34                  78                      90
150         151    Male   43                  78                      17
151         152    Male   39                  78                      88
152         153  Female   44                  78                      20
153         154  Female   38                  78                      76
154         155  Female   47                  78                      16
156         157    Male   37                  78                       1
158         159    Male   34                  78                       1
160         161  Female   56                  79                      35
163         164  Female   31                  81                      93
164         165    Male   50                  85                      26
165         166  Female   36                  85                      75
166         167    Male   42                  86                      20
167         168  Female   33                  86                      95
168         169  Female   36                  87                      27
169         170    Male   32                  87                      63
170         171    Male   40                  87                      13
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
176         177    Male   58                  88                      15
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
184         185  Female   41                  99                      39
186         187  Female   54                 101                      24
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18

In [10]:
import pandas as pd
import numpy as np
df1= pd.read_csv(r"Mall_Customers.csv")

print(df1.head())

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [17]:
df1.loc[1,"Age"] = np.nan

In [18]:
print(df1.isnull().sum())
print(df1.isnull())

CustomerID                0
Genre                     0
Age                       1
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64
     CustomerID  Genre    Age  Annual Income (k$)  Spending Score (1-100)
0         False  False  False               False                   False
1         False  False   True               False                   False
2         False  False  False               False                   False
3         False  False  False               False                   False
4         False  False  False               False                   False
..          ...    ...    ...                 ...                     ...
195       False  False  False               False                   False
196       False  False  False               False                   False
197       False  False  False               False                   False
198       False  False  False               False                   False
199       False  False  False               False                   False

[200 rows x 5 columns]

In [26]:
print(df1["Age"].isnull().sum())
print(df1["Age"].dtype)
print(type(df1))

0
float64
<class 'pandas.DataFrame'>

In [27]:
df1["Age"].fillna(df1["Age"].mean(), inplace=True)
print(df1)

     CustomerID   Genre        Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male  19.000000                  15                      39
1             2    Male  38.939698                  15                      81
2             3  Female  20.000000                  16                       6
3             4  Female  23.000000                  16                      77
4             5  Female  31.000000                  17                      40
..          ...     ...        ...                 ...                     ...
195         196  Female  35.000000                 120                      79
196         197  Female  45.000000                 126                      28
197         198    Male  32.000000                 126                      74
198         199    Male  32.000000                 137                      18
199         200    Male  30.000000                 137                      83

[200 rows x 5 columns]

C:\Users\ishik\AppData\Local\Temp\ipykernel_17540\3707474732.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1["Age"].fillna(df1["Age"].mean(), inplace=True)

In [28]:
df1["Age"]=df1["Age"].fillna(df1["Age"].mean(),inplace=True)
print(df1)

     CustomerID   Genre        Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male  19.000000                  15                      39
1             2    Male  38.939698                  15                      81
2             3  Female  20.000000                  16                       6
3             4  Female  23.000000                  16                      77
4             5  Female  31.000000                  17                      40
..          ...     ...        ...                 ...                     ...
195         196  Female  35.000000                 120                      79
196         197  Female  45.000000                 126                      28
197         198    Male  32.000000                 126                      74
198         199    Male  32.000000                 137                      18
199         200    Male  30.000000                 137                      83

[200 rows x 5 columns]

C:\Users\ishik\AppData\Local\Temp\ipykernel_17540\1755537032.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1["Age"]=df1["Age"].fillna(df1["Age"].mean(),inplace=True)

In [29]:
df1["Age"]=df1["Age"].fillna(df1["Age"].median())
print(df1)

     CustomerID   Genre        Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male  19.000000                  15                      39
1             2    Male  38.939698                  15                      81
2             3  Female  20.000000                  16                       6
3             4  Female  23.000000                  16                      77
4             5  Female  31.000000                  17                      40
..          ...     ...        ...                 ...                     ...
195         196  Female  35.000000                 120                      79
196         197  Female  45.000000                 126                      28
197         198    Male  32.000000                 126                      74
198         199    Male  32.000000                 137                      18
199         200    Male  30.000000                 137                      83

[200 rows x 5 columns]

In [ ]:
df1.duplicated() #It check there is dupliacte or not  df1.drop_duplicate()

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [ ]:
df1.sort_values("Age") #In aces order

     CustomerID   Genre   Age  Annual Income (k$)  Spending Score (1-100)
33           34    Male  18.0                  33                      92
114         115  Female  18.0                  65                      48
91           92    Male  18.0                  59                      41
65           66    Male  18.0                  48                      59
68           69    Male  19.0                  48                      59
..          ...     ...   ...                 ...                     ...
67           68  Female  68.0                  48                      48
108         109    Male  68.0                  63                      43
57           58    Male  69.0                  44                      46
70           71    Male  70.0                  49                      55
60           61    Male  70.0                  46                      56

[200 rows x 5 columns]

In [ ]:
df1.sort_values("Age",ascending=False) #In dec order

     CustomerID   Genre   Age  Annual Income (k$)  Spending Score (1-100)
70           71    Male  70.0                  49                      55
60           61    Male  70.0                  46                      56
57           58    Male  69.0                  44                      46
67           68  Female  68.0                  48                      48
108         109    Male  68.0                  63                      43
..          ...     ...   ...                 ...                     ...
111         112  Female  19.0                  63                      54
65           66    Male  18.0                  48                      59
33           34    Male  18.0                  33                      92
114         115  Female  18.0                  65                      48
91           92    Male  18.0                  59                      41

[200 rows x 5 columns]

In [36]:
df1.sort_index()

     CustomerID   Genre        Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male  19.000000                  15                      39
1             2    Male  38.939698                  15                      81
2             3  Female  20.000000                  16                       6
3             4  Female  23.000000                  16                      77
4             5  Female  31.000000                  17                      40
..          ...     ...        ...                 ...                     ...
195         196  Female  35.000000                 120                      79
196         197  Female  45.000000                 126                      28
197         198    Male  32.000000                 126                      74
198         199    Male  32.000000                 137                      18
199         200    Male  30.000000                 137                      83

[200 rows x 5 columns]

In [ ]:
df1.sort_index(ascending=False) #Rev

     CustomerID   Genre        Age  Annual Income (k$)  Spending Score (1-100)
199         200    Male  30.000000                 137                      83
198         199    Male  32.000000                 137                      18
197         198    Male  32.000000                 126                      74
196         197  Female  45.000000                 126                      28
195         196  Female  35.000000                 120                      79
..          ...     ...        ...                 ...                     ...
4             5  Female  31.000000                  17                      40
3             4  Female  23.000000                  16                      77
2             3  Female  20.000000                  16                       6
1             2    Male  38.939698                  15                      81
0             1    Male  19.000000                  15                      39

[200 rows x 5 columns]

In [40]:
df1[df1["Age"]>60]

     CustomerID   Genre   Age  Annual Income (k$)  Spending Score (1-100)
8             9    Male  64.0                  19                       3
10           11    Male  67.0                  19                      14
40           41  Female  65.0                  38                      35
57           58    Male  69.0                  44                      46
60           61    Male  70.0                  46                      56
62           63  Female  67.0                  47                      52
64           65    Male  63.0                  48                      51
67           68  Female  68.0                  48                      48
70           71    Male  70.0                  49                      55
82           83    Male  67.0                  54                      41
90           91  Female  68.0                  59                      55
102         103    Male  67.0                  62                      59
106         107  Female  66.0                  63                      50
108         109    Male  68.0                  63                      43
109         110    Male  66.0                  63                      48
110         111    Male  65.0                  63                      52
116         117  Female  63.0                  65                      43

In [41]:
df1[(df1["Age"]>60)&(df1["Age"]<80)]

     CustomerID   Genre   Age  Annual Income (k$)  Spending Score (1-100)
8             9    Male  64.0                  19                       3
10           11    Male  67.0                  19                      14
40           41  Female  65.0                  38                      35
57           58    Male  69.0                  44                      46
60           61    Male  70.0                  46                      56
62           63  Female  67.0                  47                      52
64           65    Male  63.0                  48                      51
67           68  Female  68.0                  48                      48
70           71    Male  70.0                  49                      55
82           83    Male  67.0                  54                      41
90           91  Female  68.0                  59                      55
102         103    Male  67.0                  62                      59
106         107  Female  66.0                  63                      50
108         109    Male  68.0                  63                      43
109         110    Male  66.0                  63                      48
110         111    Male  65.0                  63                      52
116         117  Female  63.0                  65                      43

In [42]:
df1[(df1["Age"]>60)|(df1["Age"]<80)]

     CustomerID   Genre        Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male  19.000000                  15                      39
1             2    Male  38.939698                  15                      81
2             3  Female  20.000000                  16                       6
3             4  Female  23.000000                  16                      77
4             5  Female  31.000000                  17                      40
..          ...     ...        ...                 ...                     ...
195         196  Female  35.000000                 120                      79
196         197  Female  45.000000                 126                      28
197         198    Male  32.000000                 126                      74
198         199    Male  32.000000                 137                      18
199         200    Male  30.000000                 137                      83

[200 rows x 5 columns]

In [60]:
df1["Bouns"]=1005
print(df1)

     CustomerID   Genre        Age  Annual Income (k$)  \
0             1    Male  19.000000                  15
1             2    Male  38.939698                  15
2             3  Female  20.000000                  16
3             4  Female  23.000000                  16
4             5  Female  31.000000                  17
..          ...     ...        ...                 ...
195         196  Female  35.000000                 120
196         197  Female  45.000000                 126
197         198    Male  32.000000                 126
198         199    Male  32.000000                 137
199         200    Male  30.000000                 137

     Spending Score (1-100)  Bouns
0                        39   1005
1                        81   1005
2                         6   1005
3                        77   1005
4                        40   1005
..                      ...    ...
195                      79   1005
196                      28   1005
197                      74   1005
198                      18   1005
199                      83   1005

[200 rows x 6 columns]

In [64]:
df1.head() #It print staring 5 index

,CustomerID,Genre,Age,Annual Income (k$),Spending Score (1-100),Bouns
0,1,Male,19.000000,15,39,1005
1,2,Male,38.939698,15,81,1005
2,3,Female,20.000000,16,6,1005
3,4,Female,23.000000,16,77,1005
4,5,Female,31.000000,17,40,1005

In [65]:
df1.tail() #It print last 5 index

,CustomerID,Genre,Age,Annual Income (k$),Spending Score (1-100),Bouns
195,196,Female,35.0,120,79,1005
196,197,Female,45.0,126,28,1005
197,198,Male,32.0,126,74,1005
198,199,Male,32.0,137,18,1005
199,200,Male,30.0,137,83,1005

In [66]:
df1.head(20) #Fisrt 20 indedx print

,CustomerID,Genre,Age,Annual Income (k$),Spending Score (1-100),Bouns
0,1,Male,19.000000,15,39,1005
1,2,Male,38.939698,15,81,1005
2,3,Female,20.000000,16,6,1005
3,4,Female,23.000000,16,77,1005
4,5,Female,31.000000,17,40,1005
5,6,Female,22.000000,17,76,1005
6,7,Female,35.000000,18,6,1005
7,8,Female,23.000000,18,94,1005
8,9,Male,64.000000,19,3,1005
9,10,Female,30.000000,19,72,1005
10,11,Male,67.000000,19,14,1005
11,12,Female,35.000000,19,99,1005
12,13,Female,58.000000,20,15,1005
13,14,Female,24.000000,20,77,1005
14,15,Male,37.000000,20,13,1005
15,16,Male,22.000000,20,79,1005
16,17,Female,35.000000,21,35,1005
17,18,Male,20.000000,21,66,1005
18,19,Male,52.000000,23,29,1005
19,20,Female,35.000000,23,98,1005

In [ ]:
df1.groupby("Annual Income (k$)")

In [78]:
groups = df1.groupby("Annual Income (k$)")   # Example
print(groups.groups)

{15: [0, 1], 16: [2, 3], 17: [4, 5], 18: [6, 7], 19: [8, 9, 10, 11], 20: [12, 13, 14, 15], 21: [16, 17], 23: [18, 19], 24: [20, 21], 25: [22, 23], 28: [24, 25, 26, 27], 29: [28, 29], 30: [30, 31], 33: [32, 33, 34, 35], 34: [36, 37], 37: [38, 39], 38: [40, 41], 39: [42, 43, 44, 45], 40: [46, 47, 48, 49], 42: [50, 51], 43: [52, 53, 54, 55], 44: [56, 57], 46: [58, 59, 60, 61], 47: [62, 63], 48: [64, 65, 66, 67, 68, 69], 49: [70, 71], 50: [72, 73], 54: [74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85], 57: [86, 87], 58: [88, 89], 59: [90, 91], 60: [92, 93, 94, 95, 96, 97], 61: [98, 99], 62: [100, 101, 102, 103, 104, 105], 63: [106, 107, 108, 109, 110, 111], 64: [112, 113], 65: [114, 115, 116, 117], 67: [118, 119, 120, 121], 69: [122, 123], 70: [124, 125], 71: [126, 127, 128, 129, 130, 131], 72: [132, 133], 73: [134, 135, 136, 137], 74: [138, 139], 75: [140, 141], 76: [142, 143], 77: [144, 145, 146, 147], 78: [148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159], 79: [160, 161], 81: [162, 163], 85: [164, 165], 86: [166, 167], 87: [168, 169, 170, 171, 172, 173], 88: [174, 175, 176, 177], 93: [178, 179], 97: [180, 181], 98: [182, 183], 99: [184, 185], 101: [186, 187], 103: [188, 189, 190, 191], 113: [192, 193], 120: [194, 195], 126: [196, 197], 137: [198, 199]}

In [80]:
df1.groupby("Annual Income (k$)")["Spending Score (1-100)"].mean()

Annual Income (k$)
15     60.0
16     41.5
17     58.0
18     50.0
19     47.0
       ...
103    48.5
113    49.5
120    47.5
126    51.0
137    50.5
Name: Spending Score (1-100), Length: 64, dtype: float64

In [ ]:
type(groups) #It give type

pandas.api.typing.DataFrameGroupBy

In [83]:
df1.groupby("Annual Income (k$)")["Spending Score (1-100)"].agg(["sum", "mean"])

                    sum  mean
Annual Income (k$)
15                  120  60.0
16                   83  41.5
17                  116  58.0
18                  100  50.0
19                  188  47.0
...                 ...   ...
103                 194  48.5
113                  99  49.5
120                  95  47.5
126                 102  51.0
137                 101  50.5

[64 rows x 2 columns]